import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use — Daily Quotes by Pastor Mrs. Oluwatosin Afolabi",
  description: "Terms of use for the Daily Quotes platform by Pastor Mrs. Oluwatosin Afolabi.",
};

const EFFECTIVE_DATE = "1 May 2025";

export default function TermsPage() {
  const sections = [
    {
      title: "1. Acceptance of Terms",
      body: `By accessing and using this website, you accept and agree to be bound by these Terms of Use.
If you do not agree to these terms, please do not use this site.`,
    },
    {
      title: "2. Use of Content",
      body: `All quotes, content, and materials on this site are for personal, non-commercial, spiritual
enrichment only. You may share quotes freely for personal encouragement, provided you credit
Pastor Mrs. Oluwatosin Afolabi and this site. Commercial reproduction or redistribution of content
without prior written permission is prohibited.`,
    },
    {
      title: "3. AI-Generated Content",
      body: `Quotes on this platform are generated by artificial intelligence guided by Christian faith
principles. While we strive for accuracy and spiritual soundness, we cannot guarantee that every
quote is perfect theology. Always weigh any quote against the full counsel of Scripture.`,
    },
    {
      title: "4. Bible Verses",
      body: `Scripture references are drawn from the King James Version (KJV) of the Bible via
bible-api.com. We do not claim ownership of Biblical text. We encourage you to verify verses in
your own Bible.`,
    },
    {
      title: "5. Advertising",
      body: `This site may display advertisements served by Google AdSense or other advertising networks.
We are not responsible for the content of third-party advertisements. The presence of an advertisement
does not constitute an endorsement.`,
    },
    {
      title: "6. Limitation of Liability",
      body: `This website and its content are provided "as is" without warranty of any kind. We shall not
be liable for any direct, indirect, incidental, or consequential damages arising from your use of the site.`,
    },
    {
      title: "7. External Links",
      body: `This site may contain links to external websites. We are not responsible for the content or
privacy practices of those sites.`,
    },
    {
      title: "8. Changes to Terms",
      body: `We reserve the right to update these Terms of Use at any time. Changes will be posted on this
page with an updated effective date. Continued use of the site constitutes acceptance of any revised terms.`,
    },
    {
      title: "9. Governing Law",
      body: `These terms are governed by the laws of the Federal Republic of Nigeria. Any disputes shall
be resolved in accordance with Nigerian law.`,
    },
  ];

  return (
    <main className="min-h-screen">
      {/* Hero */}
      <section className="relative overflow-hidden py-20 px-4">
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            background:
              "radial-gradient(ellipse 80% 50% at 50% 0%, rgba(201,168,76,0.08) 0%, transparent 70%)",
          }}
        />
        <div className="relative z-10 max-w-3xl mx-auto flex flex-col items-center text-center">
          <p className="font-lato text-xs uppercase tracking-[0.3em] text-gold/60 mb-3">Legal</p>
          <h1
            className="font-playfair italic font-bold text-4xl md:text-5xl mb-4"
            style={{
              background: "linear-gradient(135deg,#F5E6A3 0%,#C9A84C 50%,#F5E6A3 100%)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              backgroundClip: "text",
            }}
          >
            Terms of Use
          </h1>
          <p className="font-lato text-white/40 text-sm">Effective date: {EFFECTIVE_DATE}</p>
        </div>
      </section>

      {/* Content */}
      <section className="max-w-3xl mx-auto px-4 pb-20">
        <div className="glass-card rounded-2xl p-8 md:p-12 mb-8 space-y-8">
          <p className="font-lato text-white/65 leading-relaxed">
            Please read these Terms of Use carefully before using this website. By using the site,
            you agree to these terms.
          </p>

          {sections.map((s) => (
            <div key={s.title}>
              <h2
                className="font-playfair font-bold text-lg mb-3"
                style={{
                  background: "linear-gradient(135deg,#F5E6A3,#C9A84C)",
                  WebkitBackgroundClip: "text",
                  WebkitTextFillColor: "transparent",
                  backgroundClip: "text",
                }}
              >
                {s.title}
              </h2>
              <p className="font-lato text-white/65 leading-relaxed whitespace-pre-line">{s.body}</p>
            </div>
          ))}
        </div>

        <div className="text-center">
          <Link href="/" className="btn-gold inline-flex">
            ← Back to Daily Quotes
          </Link>
        </div>
      </section>
    </main>
  );
}
